"use client";

import {
  Activity, BarChart3, Bot, Building2, CalendarDays, ChevronDown, ChevronRight,
  CircleDollarSign, History, Home, Lightbulb, LogOut, Moon, MoreHorizontal,
  Rocket, Save, Settings, ShieldCheck, ShoppingBag, Sparkles, Store, Sun, Target,
  TrendingDown, TrendingUp, Truck, UserRound, UsersRound, UtensilsCrossed, X,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { calculateBonus, calculatePerformance, validateDetails } from "@/lib/calculations";
import { buildDemoAnalysis } from "@/lib/ai-demo";
import { MANAGEMENT_RULES, UNITS } from "@/lib/config";
import { formatDateBR, formatMoney, formatMoneyInput, formatPercent, parseMoney } from "@/lib/format";
import type { OperatingInputs, SalesEntry, UnitConfig, UserRole } from "@/lib/types";

type View = "dashboard" | "launch" | "history" | "ai" | "profile" | "admin";
type Theme = "light" | "dark" | "system";
const currentDate = new Date();
const firebaseConfigured = Boolean(process.env.NEXT_PUBLIC_FIREBASE_API_KEY && process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID);
const isoDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const entryTotal = (entry: SalesEntry) => entry.salao + entry.delivery + entry.ifood;

function IconForChannel({ channel }: { channel: string }) {
  if (channel === "salao") return <UtensilsCrossed size={19} />;
  if (channel === "delivery") return <Truck size={19} />;
  return <ShoppingBag size={19} />;
}

function ProgressBar({ value, expected, tone = "brand" }: { value: number; expected?: number; tone?: string }) {
  return <div className="progress-shell" role="progressbar" aria-valuenow={Math.round(value)} aria-valuemin={0} aria-valuemax={100}>
    <span className={`progress-fill tone-${tone}`} style={{ width: `${Math.min(Math.max(value, 2), 100)}%` }} />
    {expected !== undefined && <span className="progress-marker" style={{ left: `${Math.min(Math.max(expected, 1), 99)}%` }} aria-label="Trajetória esperada" />}
  </div>;
}

function ProgressRing({ value, size = 86, tone = "brand" }: { value: number; size?: number; tone?: string }) {
  const radius = 38, circumference = 2 * Math.PI * radius, progress = Math.min(Math.max(value, 0), 100);
  return <div className={`progress-ring tone-${tone}`} style={{ width: size, height: size }}>
    <svg viewBox="0 0 88 88" aria-hidden="true"><circle className="ring-track" cx="44" cy="44" r={radius} /><circle className="ring-value" cx="44" cy="44" r={radius} strokeDasharray={circumference} strokeDashoffset={circumference - (progress / 100) * circumference} /></svg>
    <strong>{Math.round(value)}%</strong>
  </div>;
}

function Trend({ value }: { value: number }) {
  const state = value > 1 ? "up" : value < -1 ? "down" : "stable";
  return <span className={`trend trend-${state}`}>{state === "up" ? <TrendingUp size={15} /> : state === "down" ? <TrendingDown size={15} /> : <MoreHorizontal size={15} />}{value > 0 ? "+" : ""}{formatPercent(value)} <small>vs. anterior</small></span>;
}

function Sparkline({ values, target }: { values: number[]; target?: number[] }) {
  if (!values.length) return <div className="spark-empty" />;
  const all = [...values, ...(target || [])], max = Math.max(...all, 1), min = Math.min(...all, 0), range = max - min || 1;
  const points = (series: number[]) => series.map((value, index) => `${(index / Math.max(series.length - 1, 1)) * 100},${46 - ((value - min) / range) * 40}`).join(" ");
  return <svg className="sparkline" viewBox="0 0 100 50" preserveAspectRatio="none" aria-label="Evolução dos últimos dias">{target && <polyline points={points(target)} className="spark-target" />}<polyline points={points(values)} className="spark-main" /></svg>;
}

function LineChart({ entries, unit }: { entries: SalesEntry[]; unit: UnitConfig }) {
  const daily = entries.slice(-14), values = daily.map(entryTotal), targets = daily.map((entry) => { const [y, m, d] = entry.date.split("-").map(Number); return unit.dailyTargets[new Date(y, m - 1, d).getDay()].total; });
  const max = Math.max(...values, ...targets, 1), x = (i: number) => 8 + (i / Math.max(daily.length - 1, 1)) * 284, y = (v: number) => 128 - (v / max) * 106;
  const points = (series: number[]) => series.map((value, index) => `${x(index)},${y(value)}`).join(" ");
  return <div className="chart-wrap"><div className="chart-legend"><span><i className="legend-real" /> Realizado</span><span><i className="legend-target" /> Meta diária</span></div><svg className="line-chart" viewBox="0 0 300 155" role="img" aria-label="Faturamento realizado comparado à meta diária">
    {[25, 55, 85, 115].map((line) => <line key={line} x1="8" x2="292" y1={line} y2={line} className="grid-line" />)}<polyline points={points(targets)} className="line-target" /><polyline points={points(values)} className="line-real" />
    {values.map((value, index) => <circle key={index} cx={x(index)} cy={y(value)} r="2.6" className="chart-dot" aria-label={`${formatDateBR(daily[index].date)}: ${formatMoney(value)}`} />)}
    {daily.map((entry, index) => (index % Math.ceil(daily.length / 5) === 0 || index === daily.length - 1) && <text key={entry.date} x={x(index)} y="151" textAnchor="middle">{entry.date.slice(-2)}</text>)}
  </svg></div>;
}

function Donut({ channels }: { channels: { label: string; realized: number; key: string }[] }) {
  const total = channels.reduce((sum, item) => sum + item.realized, 0) || 1, colors: Record<string, string> = { salao: "var(--brand)", delivery: "var(--success)", ifood: "var(--warning)" };
  const slices = channels.reduce<{ channel: typeof channels[number]; percent: number; offset: number }[]>((items, channel) => {
    const percent = (channel.realized / total) * 100, offset = items.reduce((sum, item) => sum + item.percent, 0);
    return [...items, { channel, percent, offset }];
  }, []);
  return <div className="donut-layout"><svg className="donut" viewBox="0 0 42 42" aria-label="Participação por canal"><circle cx="21" cy="21" r="15.9" fill="none" stroke="var(--surface-secondary)" strokeWidth="6" />{slices.map(({ channel, percent, offset }) => <circle key={channel.key} cx="21" cy="21" r="15.9" fill="none" stroke={colors[channel.key]} strokeWidth="6" strokeDasharray={`${percent} ${100 - percent}`} strokeDashoffset={25 - offset} />)}</svg><div className="donut-legend">{channels.map((channel) => <div key={channel.key}><i style={{ background: colors[channel.key] }} /><span>{channel.label}</span><strong>{formatPercent((channel.realized / total) * 100)}</strong></div>)}</div></div>;
}

function Dashboard({ unit, entries, onNavigate }: { unit: UnitConfig; entries: SalesEntry[]; onNavigate: (view: View) => void }) {
  const metrics = useMemo(() => calculatePerformance(unit, entries, currentDate), [unit, entries]), currentEntries = entries.filter((entry) => entry.unitId === unit.id), recent = currentEntries.slice(-7);
  const channelValues = (key: "salao" | "delivery" | "ifood") => recent.map((entry) => entry[key]);
  const statusTone = metrics.health === "green" ? "success" : metrics.health === "yellow" ? "warning" : "danger";
  const bonus = calculateBonus(unit, currentEntries, { cmvPercent: 32.8, freelancerSpend: 1180 });
  return <div className="screen-stack dashboard-screen">
    <section className="hero-card surface-card entrance"><div className="hero-topline"><span>Faturamento do mês</span><span className="live-pill"><i /> Atualizado agora</span></div><div className="hero-grid"><div><strong className="hero-value">{formatMoney(metrics.total)}</strong><p><b>{formatPercent(metrics.percentage)}</b> da meta mensal</p></div><ProgressRing value={metrics.percentage} size={96} /></div><ProgressBar value={metrics.percentage} expected={(metrics.expected / unit.monthlyGoal) * 100} /><div className="hero-foot"><div><span>Meta</span><strong>{formatMoney(unit.monthlyGoal)}</strong></div><div><span>Falta</span><strong>{formatMoney(metrics.missing)}</strong></div><div><span>Supermeta</span><strong>{formatMoney(unit.superGoal)}</strong></div></div></section>
    <section className={`health-card health-${metrics.health} entrance delay-1`}><div className="health-icon"><Activity size={23} /></div><div className="health-copy"><span className="eyebrow">Saúde da meta</span><h2>{metrics.healthLabel}</h2><p>Você está <strong>{formatMoney(Math.abs(metrics.gap))} {metrics.gap >= 0 ? "acima" : "abaixo"}</strong> da trajetória esperada.</p></div><div className="health-projection"><span>No ritmo atual</span><strong>{formatMoney(metrics.projection)}</strong></div></section>
    <section className="surface-card trajectory-card entrance delay-2"><div className="section-heading"><div><span className="eyebrow">Trajetória do mês</span><h2>Realizado x esperado</h2></div><span className={`status-badge status-${statusTone}`}>{formatPercent(metrics.trajectoryPercentage)} do ritmo</span></div><div className="trajectory-values"><div><span>Realizado</span><strong>{formatMoney(metrics.total)}</strong></div><div><span>Esperado até hoje</span><strong>{formatMoney(metrics.expected)}</strong></div><div className={metrics.gap >= 0 ? "positive" : "negative"}><span>Diferença</span><strong>{metrics.gap >= 0 ? "+" : "−"}{formatMoney(Math.abs(metrics.gap))}</strong></div></div><div className="double-track"><div><span style={{ width: `${Math.min(metrics.percentage, 100)}%` }} /></div><i style={{ left: `${Math.min((metrics.expected / unit.monthlyGoal) * 100, 99)}%` }}><em>Hoje</em></i></div></section>
    <div className="section-heading channels-heading"><div><span className="eyebrow">Performance por canal</span><h2>Onde o resultado acontece</h2></div><button className="text-button" onClick={() => onNavigate("history")}>Ver histórico <ChevronRight size={16} /></button></div>
    <section className="channel-scroller">{metrics.channels.map((channel) => <article className="channel-card surface-card" key={channel.key}><div className="channel-head"><span className={`channel-icon channel-${channel.key}`}><IconForChannel channel={channel.key} /></span><ProgressRing value={channel.percentage} size={62} tone={channel.key} /></div><span className="eyebrow">{channel.label}</span><strong className="channel-value">{formatMoney(channel.realized)}</strong><p>de {formatMoney(channel.goal)}</p><ProgressBar value={channel.percentage} tone={channel.key} /><div className="channel-bottom"><span>Faltam {formatMoney(Math.max(-channel.gap, 0))}</span><Trend value={channel.trend} /></div><Sparkline values={channelValues(channel.key)} /></article>)}</section>
    <section className="dashboard-grid"><article className="surface-card chart-card span-2"><div className="section-heading"><div><span className="eyebrow">Evolução diária</span><h2>Últimos 14 dias</h2></div><span className="chart-chip"><CalendarDays size={15} /> Agosto</span></div><LineChart entries={currentEntries} unit={unit} /></article><article className="surface-card chart-card"><div className="section-heading"><div><span className="eyebrow">Composição</span><h2>Participação</h2></div></div><Donut channels={metrics.channels} /></article></section>
    <section className="metrics-grid"><article className="surface-card compact-metric"><span className="metric-icon icon-purple"><Rocket size={19} /></span><div><span>Projeção do mês</span><strong>{formatMoney(metrics.projection)}</strong><small className={metrics.projection >= unit.monthlyGoal ? "positive" : "negative"}>{metrics.projection >= unit.monthlyGoal ? "+" : "−"}{formatMoney(Math.abs(metrics.projection - unit.monthlyGoal))} vs. meta</small></div></article><article className="surface-card compact-metric"><span className="metric-icon icon-blue"><Target size={19} /></span><div><span>Média necessária</span><strong>{formatMoney(metrics.necessaryAverage)}<small>/dia</small></strong><small>{metrics.remainingDays} dias restantes</small></div></article><article className="surface-card compact-metric"><span className="metric-icon icon-green"><BarChart3 size={19} /></span><div><span>Média últimos 7 dias</span><strong>{formatMoney(metrics.last7Average)}</strong><Trend value={metrics.weeklyEvolution} /></div></article></section>
    <section className="bonus-preview surface-card"><div className="bonus-copy"><span className="metric-icon icon-amber"><CircleDollarSign size={20} /></span><div><span className="eyebrow">Minha bonificação</span><h2>{formatMoney(bonus.conquered)} conquistados</h2><p>Potencial total de {formatMoney(bonus.potential)}</p></div></div><ProgressRing value={(bonus.conquered / bonus.potential) * 100} size={68} tone="warning" /><button className="secondary-button" onClick={() => onNavigate("profile")}>Ver detalhamento <ChevronRight size={16} /></button></section>
    <section className="ai-card"><div className="ai-glow" /><div className="ai-label"><Sparkles size={17} /> Insight House IA</div><h2>{metrics.worstChannel.label} precisa de atenção</h2><p>O canal está em {formatPercent(metrics.worstChannel.percentage)} da meta e é o principal desvio atual. A média necessária da unidade subiu para <strong>{formatMoney(metrics.necessaryAverage)}/dia</strong>.</p><div className="ai-actions"><button className="ai-primary" onClick={() => onNavigate("ai")}><Sparkles size={17} /> Ver análise completa</button><button className="ai-secondary" onClick={() => onNavigate("ai")}>Gerar plano de ação</button></div></section>
  </div>;
}

function MoneyInput({ label, value, onChange, icon }: { label: string; value: number; onChange: (value: number) => void; icon: React.ReactNode }) {
  return <label className="money-field"><span className="field-icon">{icon}</span><span className="field-copy"><b>{label}</b><small>Valor válido para a meta</small></span><span className="money-control"><i>R$</i><input inputMode="decimal" value={value ? formatMoneyInput(value) : ""} placeholder="0,00" onChange={(event) => onChange(parseMoney(event.target.value))} aria-label={`Valor de ${label}`} /></span></label>;
}

function DetailAccordion({ title, total, items, values, onChange }: { title: string; total: number; items: { key: string; label: string }[]; values: Record<string, number>; onChange: (key: string, value: number) => void }) {
  const [open, setOpen] = useState(false), validation = validateDetails(total, values);
  return <div className={`detail-accordion ${open ? "is-open" : ""}`}><button className="accordion-trigger" onClick={() => setOpen(!open)} aria-expanded={open}><span><ChevronDown size={18} /> {title}</span><small className={total && !validation.matches ? "warning-text" : "muted-text"}>{total ? (validation.matches ? "Detalhamento confere" : `Diferença de ${formatMoney(Math.abs(validation.difference))}`) : "Opcional"}</small></button>{open && <div className="accordion-body">{items.map((item) => <label className="detail-field" key={item.key}><span>{item.label}</span><div><i>R$</i><input inputMode="decimal" value={values[item.key] ? formatMoneyInput(values[item.key]) : ""} placeholder="0,00" onChange={(event) => onChange(item.key, parseMoney(event.target.value))} /></div></label>)}{total > 0 && !validation.matches && <div className="validation-box"><span>!</span><p><strong>O detalhamento não corresponde ao total.</strong> Soma {formatMoney(validation.sum)}, mas o total informado é {formatMoney(total)}.</p></div>}</div>}</div>;
}

function LaunchScreen({ unit, entries, onSave, onSync }: { unit: UnitConfig; entries: SalesEntry[]; onSave: (entry: SalesEntry) => Promise<void>; onSync: (unitId: string, date: string) => Promise<SalesEntry> }) {
  const [date, setDate] = useState(isoDate(currentDate)); const existing = entries.find((entry) => entry.unitId === unit.id && entry.date === date);
  const [salao, setSalao] = useState(existing?.salao || 0), [delivery, setDelivery] = useState(existing?.delivery || 0), [ifood, setIfood] = useState(existing?.ifood || 0);
  const [deliveryDetails, setDeliveryDetails] = useState<Record<string, number>>(existing?.deliveryDetails || {}), [ifoodDetails, setIfoodDetails] = useState<Record<string, number>>(existing?.ifoodDetails || {}), [confirm, setConfirm] = useState(false), [saving, setSaving] = useState(false), [syncing, setSyncing] = useState(false), [syncError, setSyncError] = useState("");
  const total = salao + delivery + ifood, [y, m, d] = date.split("-").map(Number), dailyTarget = unit.dailyTargets[new Date(y, m - 1, d).getDay()];
  const changeDate = (nextDate: string) => { const found = entries.find((entry) => entry.unitId === unit.id && entry.date === nextDate); setDate(nextDate); setSalao(found?.salao || 0); setDelivery(found?.delivery || 0); setIfood(found?.ifood || 0); setDeliveryDetails(found?.deliveryDetails || {}); setIfoodDetails(found?.ifoodDetails || {}); };
  const persist = async () => { setSaving(true); await onSave({ id: `${unit.id}_${date}`, unitId: unit.id, date, salao, delivery, ifood, deliveryDetails, ifoodDetails, createdBy: "gerente@house190.com.br", updatedAt: new Date().toISOString() }); setSaving(false); setConfirm(false); };
  const syncTakeat = async () => { setSyncing(true); setSyncError(""); try { const entry = await onSync(unit.id, date); setSalao(entry.salao); setDelivery(entry.delivery); setIfood(entry.ifood); setDeliveryDetails(entry.deliveryDetails || {}); setIfoodDetails(entry.ifoodDetails || {}); } catch (error) { setSyncError(error instanceof Error ? error.message : "Não foi possível sincronizar a Takeat."); } finally { setSyncing(false); } };
  const submit = () => { const dv = validateDetails(delivery, deliveryDetails), iv = validateDetails(ifood, ifoodDetails), used = Object.values(deliveryDetails).some(Boolean) || Object.values(ifoodDetails).some(Boolean); if (used && (!dv.matches || !iv.matches)) setConfirm(true); else void persist(); };
  return <div className="screen-stack narrow-screen"><div className="page-title"><div><span className="eyebrow">Lançamento diário</span><h1>Vendas do dia</h1><p>Os valores vêm automaticamente da Takeat e podem ser conferidos antes de salvar.</p></div><div className="date-picker"><CalendarDays size={17} /><input type="date" value={date} onChange={(event) => changeDate(event.target.value)} /></div></div>
    <section className="takeat-sync surface-card"><div><span className="takeat-logo">T</span><div><strong>Integração Takeat</strong><small>{existing?.source === "takeat" ? `Sincronizado · ${existing.sourceSummary?.sessions || 0} vendas` : "Importar Salão, Delivery e iFood"}</small></div></div><button className="secondary-button" onClick={() => void syncTakeat()} disabled={syncing}>{syncing ? "Sincronizando..." : "Sincronizar agora"}</button>{syncError && <p className="sync-error">{syncError}</p>}</section>
    <section className="surface-card launch-card"><div className="launch-date"><span>{formatDateBR(date)}</span><b>Meta do dia: {formatMoney(dailyTarget.total)}</b></div><div className="money-fields"><MoneyInput label="Salão" value={salao} onChange={setSalao} icon={<UtensilsCrossed size={21} />} /><MoneyInput label="Delivery próprio" value={delivery} onChange={setDelivery} icon={<Truck size={21} />} /><MoneyInput label="iFood" value={ifood} onChange={setIfood} icon={<ShoppingBag size={21} />} /></div><div className="launch-total"><div><span>Total do dia</span><strong>{formatMoney(total)}</strong></div><div><span>Meta diária</span><strong>{formatMoney(dailyTarget.total)}</strong></div><span className={`day-gap ${total >= dailyTarget.total ? "positive" : "negative"}`}>{total >= dailyTarget.total ? "+" : "−"}{formatMoney(Math.abs(total - dailyTarget.total))}</span></div><ProgressBar value={(total / dailyTarget.total) * 100} /></section>
    <section className="detail-section"><div className="section-heading"><div><span className="eyebrow">Composição analítica</span><h2>Detalhamento opcional</h2></div></div><DetailAccordion title="Detalhar Delivery" total={delivery} items={unit.channels.delivery.details} values={deliveryDetails} onChange={(key, value) => setDeliveryDetails((current) => ({ ...current, [key]: value }))} /><DetailAccordion title="Detalhar iFood" total={ifood} items={unit.channels.ifood.details} values={ifoodDetails} onChange={(key, value) => setIfoodDetails((current) => ({ ...current, [key]: value }))} /></section>
    <div className="form-note"><ShieldCheck size={18} /><p>Frete, brindes, cancelamentos, estornos e receitas de terceiros não devem entrar nos valores.</p></div><button className="primary-button save-button" onClick={submit} disabled={saving || total <= 0}><Save size={19} />{saving ? "Salvando..." : existing ? "Atualizar vendas" : "Salvar vendas"}</button>
    {confirm && <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="confirm-modal surface-card"><button className="modal-close" onClick={() => setConfirm(false)} aria-label="Fechar"><X size={20} /></button><span className="modal-icon">!</span><h2>Detalhamento diferente do total</h2><p>Uma subdivisão não fecha com o valor principal. O faturamento continuará considerando apenas os canais principais, sem duplicar valores.</p><div><button className="secondary-button" onClick={() => setConfirm(false)}>Corrigir valores</button><button className="danger-confirm" onClick={() => void persist()}>Confirmar mesmo assim</button></div></div></div>}
  </div>;
}

function HistoryScreen({ unit, entries }: { unit: UnitConfig; entries: SalesEntry[] }) {
  const [period, setPeriod] = useState("month"), unitEntries = entries.filter((entry) => entry.unitId === unit.id).slice().reverse(), visible = period === "today" ? unitEntries.slice(0, 1) : period === "7" ? unitEntries.slice(0, 7) : unitEntries, total = visible.reduce((sum, entry) => sum + entryTotal(entry), 0);
  return <div className="screen-stack"><div className="page-title"><div><span className="eyebrow">Histórico</span><h1>Evolução das vendas</h1><p>Entenda dias fortes, quedas e recuperação.</p></div></div><div className="segmented-control" role="tablist">{[["today","Hoje"],["7","7 dias"],["month","Mês"]].map(([key,label]) => <button key={key} className={period === key ? "active" : ""} onClick={() => setPeriod(key)}>{label}</button>)}</div>
    <section className="history-summary surface-card"><div><span>Faturamento no período</span><strong>{formatMoney(total)}</strong></div><div><span>Média por dia</span><strong>{formatMoney(total / Math.max(visible.length, 1))}</strong></div><div><span>Melhor dia</span><strong>{visible.length ? formatMoney(Math.max(...visible.map(entryTotal))) : formatMoney(0)}</strong></div></section>
    <section className="surface-card history-list"><div className="section-heading"><div><span className="eyebrow">Lançamentos</span><h2>{visible.length} dias registrados</h2></div></div>{visible.map((entry) => { const [year, month, day] = entry.date.split("-").map(Number), target = unit.dailyTargets[new Date(year, month - 1, day).getDay()].total, result = entryTotal(entry), monthNames = ["jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez"]; return <article className="history-row" key={entry.id}><div className="history-date"><strong>{day}</strong><span>{monthNames[month - 1]}</span></div><div className="history-main"><div><strong>{formatMoney(result)}</strong><span>Meta {formatMoney(target)}</span></div><ProgressBar value={(result / target) * 100} /><small>Salão {formatMoney(entry.salao)} · Delivery {formatMoney(entry.delivery)} · iFood {formatMoney(entry.ifood)}</small></div><span className={`status-dot ${result >= target ? "green" : result >= target * .93 ? "yellow" : "red"}`} /></article>; })}</section>
  </div>;
}

type AIResult = { diagnostic: string; alert: string; numbers: string[]; actions: string[]; tomorrow: string; demo?: boolean };
function AIScreen({ unit, entries }: { unit: UnitConfig; entries: SalesEntry[] }) {
  const metrics = calculatePerformance(unit, entries, currentDate); const [result, setResult] = useState<AIResult | null>(null), [loading, setLoading] = useState(false), [prompt, setPrompt] = useState("Analisar minha performance");
  const analyze = async (intent: string) => { setLoading(true); setPrompt(intent); const [salao, delivery, ifood] = metrics.channels; const payload = { solicitacao: intent, unidade: unit.name, metaMensal: unit.monthlyGoal, superMeta: unit.superGoal, faturamentoAtual: metrics.total, metaEsperadaAteHoje: metrics.expected, gap: metrics.gap, projecao: metrics.projection, diasRestantes: metrics.remainingDays, mediaNecessaria: metrics.necessaryAverage, tendencia7Dias: metrics.weeklyEvolution, salao: { label: salao.label, realizado: salao.realized, meta: salao.goal }, delivery: { label: delivery.label, realizado: delivery.realized, meta: delivery.goal }, ifood: { label: ifood.label, realizado: ifood.realized, meta: ifood.goal }, regras: MANAGEMENT_RULES };
    try { const response = await fetch("https://house-gestao-ia.gleucedias1.workers.dev/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(); setResult(data); } catch { setResult({ diagnostic: "Não foi possível gerar a análise agora.", alert: "Verifique a conexão e tente novamente.", numbers: [], actions: [], tomorrow: "Atualize os dados e tente novamente." }); } finally { setLoading(false); } };
  return <div className="screen-stack ai-screen"><div className="page-title"><div><span className="eyebrow">House IA</span><h1>Consultor de performance</h1><p>Análises baseadas somente nos números calculados pelo sistema.</p></div></div><section className="ai-command-card"><div className="ai-orb"><Bot size={30} /></div><div><span className="ai-label"><Sparkles size={15} /> Analista de gestão</span><h2>Qual decisão você precisa tomar?</h2><p>A IA interpreta trajetória, canais, tendência, projeção e regras do programa.</p></div></section><div className="ai-prompt-grid">{["Analisar minha performance", "Como recuperar minha meta?", "Gerar plano de ação", "Analisar últimos 7 dias", "O que está prejudicando minha meta?", "Como alcançar a supermeta?"].map((item) => <button key={item} onClick={() => void analyze(item)}><Lightbulb size={17} /><span>{item}</span><ChevronRight size={16} /></button>)}</div>
    {(loading || result) && <section className="analysis-result surface-card"><div className="analysis-header"><div><span className="eyebrow">Análise solicitada</span><h2>{prompt}</h2></div>{result?.demo && <span className="demo-badge">Modo demonstração</span>}</div>{loading ? <div className="analysis-skeleton">{[1,2,3,4].map((item) => <div key={item}><i /><i /><i /></div>)}</div> : result && <div className="analysis-sections"><article><span className="analysis-number">01</span><div><h3>Diagnóstico</h3><p>{result.diagnostic}</p></div></article><article className="alert-section"><span className="analysis-number">02</span><div><h3>Principal alerta</h3><p>{result.alert}</p></div></article><article><span className="analysis-number">03</span><div><h3>Números importantes</h3><ul>{result.numbers?.map((number) => <li key={number}>{number}</li>)}</ul></div></article><article><span className="analysis-number">04</span><div><h3>Plano de ação</h3><ol>{result.actions?.map((action, index) => <li key={action}><b>{index + 1}</b>{action}</li>)}</ol></div></article><article className="focus-section"><span className="analysis-number"><Target size={18} /></span><div><h3>Foco para amanhã</h3><p>{result.tomorrow}</p></div></article></div>}</section>}
  </div>;
}

function ProfileScreen({ unit, entries, role, profile, onLogout }: { unit: UnitConfig; entries: SalesEntry[]; role: UserRole; profile: { name: string; email: string }; onLogout: () => void }) {
  const [operating, setOperating] = useState<OperatingInputs>({ cmvPercent: 32.8, freelancerSpend: 1180 }), bonus = calculateBonus(unit, entries.filter((entry) => entry.unitId === unit.id), operating);
  return <div className="screen-stack"><div className="page-title"><div><span className="eyebrow">Performance e perfil</span><h1>Minha bonificação</h1><p>Regras aplicadas automaticamente à apuração.</p></div></div><section className="bonus-hero surface-card"><div><span className="eyebrow">Bônus conquistado</span><strong>{formatMoney(bonus.conquered)}</strong><p>de {formatMoney(bonus.potential)} possíveis</p></div><ProgressRing value={(bonus.conquered / bonus.potential) * 100} size={104} tone="warning" /></section>{(bonus.cmvBlocked || bonus.minimumBlocked) && <div className="blocking-alert"><ShieldCheck size={20} /><div><strong>Bonificação bloqueada</strong><p>{bonus.cmvBlocked ? "O CMV está acima do limite de 35%." : "É necessário atingir pelo menos duas categorias."}</p></div></div>}
    <section className="bonus-list surface-card"><div className="section-heading"><div><span className="eyebrow">Categorias</span><h2>Progresso da apuração</h2></div></div>{bonus.categories.map((category) => <article key={category.label}><div className="bonus-status"><span className={category.unlocked ? "done" : category.percentage >= 80 ? "near" : "far"}>{category.unlocked ? "✓" : Math.round(category.percentage) + "%"}</span><div><strong>{category.label}</strong><small>{formatMoney(category.realized)} de {formatMoney(category.goal)}</small></div></div><div className="bonus-amount"><span>{category.unlocked ? "Conquistado" : "Potencial"}</span><strong>{formatMoney(category.bonus)}</strong></div></article>)}</section>
    <section className="surface-card operating-card"><div className="section-heading"><div><span className="eyebrow">Critérios operacionais</span><h2>CMV e freelancers</h2></div></div><div className="operating-inputs"><label><span>CMV do mês</span><div><input type="number" step="0.1" value={operating.cmvPercent} onChange={(event) => setOperating({ ...operating, cmvPercent: Number(event.target.value) })} /><i>%</i></div><small>Máximo permitido: 35%</small></label><label><span>Freelancers</span><div><i>R$</i><input type="number" value={operating.freelancerSpend} onChange={(event) => setOperating({ ...operating, freelancerSpend: Number(event.target.value) })} /></div><small>Limite: R$ 1.500</small></label></div></section>
    <section className="surface-card profile-card"><div className="avatar-large">{profile.name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div><div><strong>{profile.name || "Usuário House"}</strong><span>{profile.email}</span><small>{role === "admin" ? "Acesso a todas as unidades" : unit.name}</small></div><span className="profile-role">{role === "admin" ? "Administrador" : "Gerente"}</span><button className="logout-button" onClick={onLogout}><LogOut size={17} /> Sair da conta</button></section>
  </div>;
}

function AdminScreen({ entries, onUnit }: { entries: SalesEntry[]; onUnit: (unit: UnitConfig) => void }) {
  const cards = UNITS.map((unit) => ({ unit, metrics: calculatePerformance(unit, entries, currentDate) })).sort((a, b) => b.metrics.trajectoryPercentage - a.metrics.trajectoryPercentage);
  return <div className="screen-stack"><div className="page-title"><div><span className="eyebrow">Painel administrativo</span><h1>Visão geral das unidades</h1><p>Compare performance, risco e distância da trajetória.</p></div><button className="secondary-button"><UsersRound size={17} /> Gerenciar equipe</button></div><section className="admin-overview"><article className="surface-card"><span>Faturamento consolidado</span><strong>{formatMoney(cards.reduce((sum, card) => sum + card.metrics.total, 0))}</strong><Trend value={2.8} /></article><article className="surface-card"><span>Unidades no ritmo</span><strong>{cards.filter((card) => card.metrics.health === "green").length} de 3</strong><small>Atualizado em 14 de agosto</small></article><article className="surface-card"><span>Bonificação potencial</span><strong>{formatMoney(9000)}</strong><small>Máximo das três unidades</small></article></section>
    <section className="unit-admin-grid">{cards.map(({ unit, metrics }, index) => <button className="unit-admin-card surface-card" key={unit.id} onClick={() => onUnit(unit)}><div className="unit-rank">#{index + 1}</div><div className="unit-card-head"><span className="unit-logo"><Building2 size={21} /></span><div><strong>{unit.name}</strong><span className={`status-badge status-${metrics.health === "green" ? "success" : metrics.health === "yellow" ? "warning" : "danger"}`}>{metrics.healthLabel}</span></div></div><div className="unit-main-metric"><span>Realizado</span><strong>{formatMoney(metrics.total)}</strong></div><ProgressBar value={metrics.percentage} expected={(metrics.expected / unit.monthlyGoal) * 100} /><div className="unit-stats"><div><span>Trajetória</span><strong>{formatPercent(metrics.trajectoryPercentage)}</strong></div><div><span>Gap</span><strong className={metrics.gap >= 0 ? "positive" : "negative"}>{metrics.gap >= 0 ? "+" : "−"}{formatMoney(Math.abs(metrics.gap))}</strong></div><div><span>Projeção</span><strong>{formatMoney(metrics.projection)}</strong></div></div><span className="unit-open">Abrir unidade <ChevronRight size={16} /></span></button>)}</section>
  </div>;
}

function AppNavigation({ view, setView, role, profile, onLogout }: { view: View; setView: (view: View) => void; role: UserRole; profile: { name: string; email: string }; onLogout: () => void }) {
  const items: { key: View; label: string; icon: React.ReactNode }[] = [{ key: "dashboard", label: "Início", icon: <Home size={20} /> }, { key: "history", label: "Histórico", icon: <History size={20} /> }, { key: "ai", label: "House IA", icon: <Sparkles size={20} /> }, { key: "profile", label: "Perfil", icon: <UserRound size={20} /> }];
  return <><aside className="sidebar"><div className="brand"><span className="brand-mark"><BarChart3 size={23} /></span><div><strong>HOUSE GESTÃO</strong><small>Central de Metas</small></div></div><nav>{role === "admin" && <button className={view === "admin" ? "active" : ""} onClick={() => setView("admin")}><Building2 size={20} /><span>Visão geral</span></button>}{items.map((item) => <button key={item.key} className={view === item.key ? "active" : ""} onClick={() => setView(item.key)}>{item.icon}<span>{item.label === "Início" ? "Dashboard" : item.label}</span></button>)}</nav><div className="sidebar-bottom"><button><Settings size={19} /> Configurações</button><div className="sidebar-user"><div className="avatar">{profile.name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div><div><strong>{profile.name || "Usuário House"}</strong><span>{role === "admin" ? "Administrador" : "Gerente"}</span></div><button className="logout-icon" onClick={onLogout} aria-label="Sair da conta"><LogOut size={17} /></button></div></div></aside><nav className="bottom-nav">{items.map((item) => <button key={item.key} className={view === item.key ? "active" : ""} onClick={() => setView(item.key)}>{item.icon}<span>{item.label}</span></button>)}</nav></>;
}

function LoginScreen({ onLogin, error, loading }: { onLogin: (email: string, password: string) => Promise<void>; error: string; loading: boolean }) {
  const [email, setEmail] = useState(""), [password, setPassword] = useState("");
  return <main className="login-screen"><section className="login-panel"><div className="login-brand"><span className="brand-mark"><BarChart3 size={26} /></span><div><strong>HOUSE GESTÃO</strong><small>Central de Metas e Performance</small></div></div><div className="login-copy"><span className="eyebrow">Acesso seguro</span><h1>Bem-vindo de volta</h1><p>Entre para acompanhar a performance da sua unidade.</p></div><form onSubmit={(event) => { event.preventDefault(); void onLogin(email, password); }}><label><span>E-mail</span><input type="email" required autoComplete="email" placeholder="seuemail@house190.com.br" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label><span>Senha</span><input type="password" required autoComplete="current-password" placeholder="Sua senha" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error && <div className="login-error">{error}</div>}<button className="primary-button" disabled={loading}>{loading ? "Entrando..." : "Entrar no HOUSE GESTÃO"}</button></form><div className="login-safe"><ShieldCheck size={16} /><span>Seus dados são protegidos pelo Firebase Authentication.</span></div></section><aside className="login-visual"><div className="login-glow" /><span className="ai-label"><Sparkles size={15} /> Gestão que antecipa decisões</span><h2>Transforme números diários em crescimento.</h2><p>Trajetória, canais, projeção, bonificação e plano de ação em um único lugar.</p><div className="login-mock"><div><span>Meta no ritmo</span><strong>106,7%</strong></div><ProgressBar value={68} expected={63} /><small>Resultado acima da trajetória esperada</small></div></aside></main>;
}

export default function HomePage() {
  const [view, setView] = useState<View>("dashboard"), [role, setRole] = useState<UserRole>("manager"), [unit, setUnit] = useState<UnitConfig>(UNITS[0]), [entries, setEntries] = useState<SalesEntry[]>([]), [theme, setTheme] = useState<Theme>("system"), [toast, setToast] = useState<string | null>(null), [unitMenu, setUnitMenu] = useState(false), [loaded, setLoaded] = useState(false);
  const [authState, setAuthState] = useState<"checking" | "signedout" | "signedin">("checking"), [loginError, setLoginError] = useState(""), [loginLoading, setLoginLoading] = useState(false), [profile, setProfile] = useState({ name: "", email: "" });
  useEffect(() => { const id = window.requestAnimationFrame(() => { setLoaded(true); const saved = window.localStorage.getItem("house-theme") as Theme | null; if (saved) setTheme(saved); }); return () => window.cancelAnimationFrame(id); }, []);
  useEffect(() => { if (!loaded) return; window.localStorage.setItem("house-theme", theme); document.documentElement.dataset.theme = theme; }, [theme, loaded]);
  useEffect(() => { if (toast) { const id = window.setTimeout(() => setToast(null), 3200); return () => window.clearTimeout(id); } }, [toast]);
  useEffect(() => {
    if (!firebaseConfigured) { setAuthState("signedout"); return; }
    let unsubscribe: undefined | (() => void);
    void (async () => {
      const [{ auth }, { onAuthStateChanged }, { loadUserProfile, loadUnitSales }] = await Promise.all([import("@/lib/firebase"), import("firebase/auth"), import("@/lib/firestore-service")]);
      if (!auth) return setAuthState("signedout");
      unsubscribe = onAuthStateChanged(auth, async (user) => {
        if (!user) { setEntries([]); setProfile({ name: "", email: "" }); setAuthState("signedout"); return; }
        const profile = await loadUserProfile(user.uid);
        if (!profile?.role) { setLoginError("Seu perfil ainda não foi liberado pelo administrador."); setAuthState("signedout"); return; }
        setRole(profile.role); setProfile({ name: profile.name || user.email || "Usuário House", email: profile.email || user.email || "" });
        const monthPrefix = isoDate(currentDate).slice(0, 7);
        if (profile.role === "admin") {
          const salesByUnit = await Promise.all(UNITS.map((item) => loadUnitSales(item.id, monthPrefix)));
          setEntries(salesByUnit.flat());
          setView("admin");
        } else if (profile.unitId) {
          const assigned = UNITS.find((item) => item.id === profile.unitId);
          if (assigned) {
            setUnit(assigned);
            setEntries(await loadUnitSales(assigned.id, monthPrefix));
          }
        }
        setAuthState("signedin");
        const automaticUnits = profile.role === "admin" ? UNITS.map((item) => item.id) : profile.unitId ? [profile.unitId] : [];
        void (async () => {
          try {
            const [{ syncTakeatSale }, { saveDailySale }] = await Promise.all([import("@/lib/takeat-service"), import("@/lib/firestore-service")]);
            const results = await Promise.allSettled(automaticUnits.map(async (unitId) => { const entry = await syncTakeatSale(unitId, isoDate(currentDate)); await saveDailySale(entry); return entry; }));
            const synchronized = results.filter((result): result is PromiseFulfilledResult<SalesEntry> => result.status === "fulfilled").map((result) => result.value);
            if (!synchronized.length) return;
            setEntries((current) => [...current.filter((item) => !synchronized.some((entry) => entry.unitId === item.unitId && entry.date === item.date)), ...synchronized].sort((a, b) => a.date.localeCompare(b.date)));
          } catch {
            // A tela continua disponível quando uma unidade ainda não possui credenciais Takeat.
          }
        })();
      });
    })();
    return () => unsubscribe?.();
  }, []);
  const login = async (email: string, password: string) => { setLoginLoading(true); setLoginError(""); try { const [{ auth }, { signInWithEmailAndPassword }] = await Promise.all([import("@/lib/firebase"), import("firebase/auth")]); if (!auth) throw new Error(); await signInWithEmailAndPassword(auth, email, password); } catch { setLoginError("E-mail ou senha inválidos. Confira os dados e tente novamente."); } finally { setLoginLoading(false); } };
  const logout = async () => { const [{ auth }, { signOut }] = await Promise.all([import("@/lib/firebase"), import("firebase/auth")]); if (auth) await signOut(auth); setEntries([]); setView("dashboard"); setUnit(UNITS[0]); };
  const save = async (entry: SalesEntry) => { const normalized = { ...entry, source: entry.source || "manual" } as SalesEntry; if (firebaseConfigured) { const { saveDailySale } = await import("@/lib/firestore-service"); await saveDailySale(normalized); } setEntries((current) => [...current.filter((item) => !(item.unitId === normalized.unitId && item.date === normalized.date)), normalized].sort((a, b) => a.date.localeCompare(b.date))); setToast(`Vendas de ${formatDateBR(normalized.date)} registradas com sucesso.`); setView("dashboard"); };
  const syncTakeat = async (unitId: string, date: string) => { const [{ syncTakeatSale }, { saveDailySale }] = await Promise.all([import("@/lib/takeat-service"), import("@/lib/firestore-service")]); const entry = await syncTakeatSale(unitId, date); await saveDailySale(entry); setEntries((current) => [...current.filter((item) => !(item.unitId === entry.unitId && item.date === entry.date)), entry].sort((a, b) => a.date.localeCompare(b.date))); setToast(`Takeat sincronizada: ${formatMoney(entry.salao + entry.delivery + entry.ifood)} em ${formatDateBR(entry.date)}.`); return entry; };
  const switchTheme = () => setTheme((current) => current === "system" ? "light" : current === "light" ? "dark" : "system"); const pickUnit = (next: UnitConfig) => { setUnit(next); setUnitMenu(false); setView("dashboard"); };
  if (authState === "checking") return <div className="app-loading"><span className="brand-mark"><BarChart3 size={25} /></span><div><i /><i /><i /></div></div>;
  if (authState === "signedout") return <LoginScreen onLogin={login} error={loginError} loading={loginLoading} />;
  return <div className="app-shell"><AppNavigation view={view} setView={setView} role={role} profile={profile} onLogout={() => void logout()} /><main className="app-main"><header className="topbar"><div className="mobile-brand"><span className="brand-mark"><BarChart3 size={20} /></span><strong>HOUSE GESTÃO</strong></div><div className="unit-selector-wrap"><button className="unit-selector" onClick={() => role === "admin" && setUnitMenu(!unitMenu)}><span className="unit-mini-logo"><Store size={18} /></span><div><small>Unidade atual</small><strong>{unit.name}</strong></div>{role === "admin" && <ChevronDown size={17} />}</button>{unitMenu && <div className="unit-menu">{UNITS.map((item) => <button key={item.id} className={item.id === unit.id ? "active" : ""} onClick={() => pickUnit(item)}><span><Building2 size={17} /></span><div><strong>{item.name}</strong><small>{formatMoney(item.monthlyGoal)} de meta</small></div>{item.id === unit.id && <i>✓</i>}</button>)}</div>}</div><div className="topbar-actions"><button className="icon-button" onClick={switchTheme} aria-label="Alternar tema">{theme === "dark" ? <Moon size={19} /> : theme === "light" ? <Sun size={19} /> : <Activity size={19} />}</button><button className="avatar-button" aria-label="Abrir perfil" onClick={() => setView("profile")}><span>GC</span><i /></button></div></header><div className="content-wrap">{view === "dashboard" && <Dashboard unit={unit} entries={entries} onNavigate={setView} />}{view === "history" && <HistoryScreen unit={unit} entries={entries} />}{view === "ai" && <AIScreen unit={unit} entries={entries} />}{view === "profile" && <ProfileScreen unit={unit} entries={entries} role={role} profile={profile} onLogout={() => void logout()} />}{view === "admin" && <AdminScreen entries={entries} onUnit={pickUnit} />}</div></main>{toast && <div className="toast"><span>✓</span><div><strong>Vendas sincronizadas</strong><p>{toast}</p></div><button onClick={() => setToast(null)}><X size={16} /></button></div>}</div>;
}
